INSERT INTO tb_user (name, email, phone, password) VALUES ('João Silva', 'joao.silva@email.com', '2199999999', 'senha123');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Maria Souza', 'maria.souza@email.com', '1188888888', 'mypass');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Carlos Oliveira', 'carlos.oliveira@email.com', '3177777777', 'secret');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Ana Pereira', 'ana.pereira@email.com', '4166666666', 'secure1');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Ricardo Gomes', 'ricardo.gomes@email.com', '5155555555', 'testpass');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Fernanda Costa', 'fernanda.costa@email.com', '6144444444', 'strongpwd');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Pedro Rodrigues', 'pedro.rodrigues@email.com', '7133333333', 'mysecret');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Juliana Almeida', 'juliana.almeida@email.com', '8122222222', 'password');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Lucas Martins', 'lucas.martins@email.com', '9111111111', 'simple1');
INSERT INTO tb_user (name, email, phone, password) VALUES ('Patrícia Nunes', 'patricia.nunes@email.com', '2700000000', 'another');

INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:00:00Z', 1, 1);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:05:30Z', 2, 2);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:10:45Z', 2, 3);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:15:15Z', 3, 1);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:20:00Z', 4, 4);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:25:20Z', 5, 2);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:30:50Z', 1, 5);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:35:05Z', 2, 3);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:40:30Z', 5, 6);
INSERT INTO tb_order (moment, order_status, client_id) VALUES ('2025-05-13T19:45:00Z', 4, 10);

INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Clothing');
INSERT INTO tb_category (name) VALUES ('Home & Kitchen');
INSERT INTO tb_category (name) VALUES ('Sports & Outdoors');
INSERT INTO tb_category (name) VALUES ('Beauty & Personal Care');
INSERT INTO tb_category (name) VALUES ('Toys & Games');
INSERT INTO tb_category (name) VALUES ('Automotive');
INSERT INTO tb_category (name) VALUES ('Health & Household');
INSERT INTO tb_category (name) VALUES ('Tools & Home Improvement');